config/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import dashboard

urlpatterns = [
    # home
    path("", dashboard, name="dashboard"),
    # admin
    path("admin/panel/", admin.site.urls),
    # accounts
    path("accounts/", include("accounts.urls")),
    # tasks
    path("tasks/", include("tasks.urls")),
]

tasks/urls.py
from django.urls import path

from .views import (
    create_user_task_assign,
    subtasks_list,
    swod_analysis,
    tasks_list,
    user_task_assigments,
)

urlpatterns = [
    path("", tasks_list, name="tasks_list"),
    path("swod/", swod_analysis, name="swod_analysis"),
    path("subtasks/<int:task_id>/", subtasks_list, name="subtasks_list"),
    # Assigning a task to a user
    path(
        "create/assign/<int:task_id>/<int:staff_id>/",
        create_user_task_assign,
        name="rate_user_task_assign",
    ),
    path(
        "assigments/<int:user_id>/<int:task_id>/",
        user_task_assigments,
        name="user_task_assigments",
    ),
]

accounts/models.py
# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from common.models import BaseModel

from .manager import CustomUserManager


class Project(BaseModel):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = _("Project")
        verbose_name_plural = _("Projects")


class UserRole(models.TextChoices):
    SUPERADMIN = "superadmin", _("SuperAdmin")
    ADMIN = "admin", _("Admin")
    USER = "user", _("User")


class UserStatus(models.TextChoices):
    ACTIVE = "active", _("Active")
    FIRED = "fired", _("Fired")
    HOLIDAY = "holiday", _("Holiday")


class UserPosition(models.TextChoices):
    JUNIOR = "junior", _("Yetakchi  mutaxassis")
    MIDDLE = "middle", _("Bosh mutaxassis")
    SENIOR = "senior", _("Loyiha rahbari")


class CustomUser(AbstractUser):
    username = models.CharField(max_length=150, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(_("email address"), unique=True)
    role = models.CharField(
        max_length=20, choices=UserRole.choices, default=UserRole.USER
    )
    # projects = models.ManyToManyField(Project, related_name="users", blank=True)
    current_project = models.ForeignKey(
        Project, on_delete=models.SET_NULL, related_name="users", null=True, blank=True
    )
    position = models.CharField(
        max_length=20, choices=UserPosition.choices, default=UserPosition.JUNIOR
    )
    birth_date = models.DateField(null=True, blank=True)
    salary = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    status = models.CharField(
        max_length=20, choices=UserStatus.choices, default=UserStatus.ACTIVE
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["phone"]

    objects = CustomUserManager()

    def __str__(self):
        return f"{self.email}"

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = _("CustomUser")
        verbose_name_plural = _("CustomUsers")


class UserAttendance(BaseModel):
    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="attendances"
    )

    date = models.DateField()
    late_entry_time = models.CharField("Late Entry Time", max_length=255)
    early_exit_time = models.CharField("Early Exit Time", max_length=255)
    penalty = models.PositiveIntegerField(default=0)

    @property
    def total_minutes(self):
        return self.late_entry_time + self.early_exit_time

    def __str__(self):
        return f"{self.user} - {self.date}"

    class Meta:
        verbose_name = _("UserAttendance")
        verbose_name_plural = _("UserAttendances")
        unique_together = ("user", "date")

tasks/views/swod.py
from django.contrib.auth.decorators import login_required
from django.db import models
from django.db.models import Sum, Value
from django.db.models.functions import Coalesce
from django.shortcuts import render

from accounts.models import CustomUser, Project, UserPosition, UserRole
from tasks.models import SubTasks, TaskAssignee, Tasks


@login_required
def swod_analysis(request):
    from_date = request.GET.get("from_date", "")
    to_date = request.GET.get("to_date", "")
    # Get all the users
    users = CustomUser.objects.filter(is_active=True, role=UserRole.USER).order_by(
        "position"
    )

    # Get all the tasks
    tasks = Tasks.objects.filter(is_active=True)

    # Get all the subtasks
    subtasks = SubTasks.objects.filter(is_active=True)

    # Get all the projects
    projects = Project.objects.filter(is_active=True)

    # Create a dictionary to store the ratings
    ratings = {}
    user_totals = {}

    # Iterate over all the users
    for user in users:

        # Create a dictionary to store the ratings of the user
        user_ratings = {}

        total_rating = 0  # Initialize total rating

        # Iterate over all the tasks
        for task in tasks:
            # Get all the subtasks of the task
            task_subtasks = subtasks.filter(task=task)

            # Get all the ratings of the user for the subtasks
            user_subtask_ratings = TaskAssignee.objects.filter(
                user=user, subtask__in=task_subtasks
            )
            if from_date != "" and to_date != "":
                user_subtask_ratings = user_subtask_ratings.filter(
                    date__range=[from_date, to_date]
                )

            # Calculate the sum of the ratings
            total_task_rating = user_subtask_ratings.aggregate(
                total_rating=Coalesce(
                    Sum("rating"), Value(0), output_field=models.FloatField()
                )
            )["total_rating"]

            # Add the task rating to the user ratings
            user_ratings[task.title] = round(total_task_rating,2)
            total_rating += total_task_rating  # Add task rating to the total

        # Add the user ratings and total rating to the ratings dictionary
        ratings[user.id] = user_ratings  # Store by user ID
        user_totals[user.id] = round(total_rating, 2)

    # calculate the average of company
    company_total_avg = sum(user_totals.values()) / len(user_totals)

    # group user by current_project and calculate the average of each project by user user_totals
    project_avg = {}

    for project in projects:
        project_users = CustomUser.objects.filter(
            role=UserRole.USER, current_project=project
        )
        project_total = sum(
            user_totals[user.id]
            for user in project_users
            if user_totals[user.id] is not None
        )
        project_avg[project.id] = (
            project_total / len(project_users) if len(project_users) > 0 else 1
        )
    # get which project value is greater than company average
    project_above_avg = {}
    for key, value in project_avg.items():
        if value > company_total_avg:
            project_above_avg[key] = value
    # add how much above average to each user total
    users_bonus = {}
    for user in users:
        if user.current_project:
            pr_avr = project_above_avg.get(user.current_project.id)
            if pr_avr and user_totals[user.id] > pr_avr:
                bonus = pr_avr * 0.1
                users_bonus[user.id] = round(bonus, 2)
                user_totals[user.id] += bonus
                # update round value
                user_totals[user.id] = round(user_totals[user.id], 2)

            elif pr_avr:
                bonus = pr_avr * 0.05
                users_bonus[user.id] = round(bonus, 2)
                user_totals[user.id] += bonus
                # update round value
                user_totals[user.id] = round(user_totals[user.id], 2)

    # By user level find max user_totals and set it 100% then calculate other same level users percentage
    j_user = UserPosition.JUNIOR
    m_user = UserPosition.MIDDLE
    s_user = UserPosition.SENIOR
    j_user_totals = {}
    m_user_totals = {}
    s_user_totals = {}
    for user in users:
        if user.position == j_user:
            j_user_totals[user.id] = user_totals[user.id]
        if user.position == m_user:
            m_user_totals[user.id] = user_totals[user.id]
        if user.position == s_user:
            s_user_totals[user.id] = user_totals[user.id]

    j_max = max(j_user_totals.values()) if j_user_totals else None
    m_max = max(m_user_totals.values()) if m_user_totals else None
    s_max = max(s_user_totals.values()) if s_user_totals else None

    users_kpi = {}

    for user in users:
        if user.position == j_user:
            # formula: (user_total / max_total) * 100
            users_kpi[user.id] = (
                round((user_totals[user.id] / j_max) * 100, 2) if j_max else 0
            )
        if user.position == m_user:
            users_kpi[user.id] = (
                round((user_totals[user.id] / m_max) * 100, 2) if m_max else 0
            )
        if user.position == s_user:
            users_kpi[user.id] = (
                round((user_totals[user.id] / s_max) * 100, 2) if s_max else 0
            )

    context = {
        "users": users,
        "tasks": tasks,
        "ratings": ratings,  # Passing ratings dictionary by user ID
        "user_totals": user_totals,  # Passing user totals by user ID
        "users_bonus": users_bonus,  # Passing user bonus by user ID
        "users_kpi": users_kpi,  # Passing user KPI by user ID
        "company_total_avg": round(company_total_avg, 2),
        "users_total": round(sum(user_totals.values()), 2),
        "total_users_bonus": round(sum(users_bonus.values()), 2),
        "project_avg": project_avg,
        "project_above_avg": project_above_avg,
        "from_date": from_date,
        "to_date": to_date,
    }

    return render(request, "tasks/swod_analysis.html", context)

tasks/views/task_assignees.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from django.shortcuts import get_object_or_404, redirect, render

from accounts.models import CustomUser
from tasks.models import SubTasks, TaskAssignee, Tasks


@login_required
def create_user_task_assign(request, task_id, staff_id):
    try:
        task = Tasks.objects.get(id=task_id)
        staff_user = CustomUser.objects.get(id=staff_id)

        # Prefetch TaskAssignee for the current user
        rated_subtasks = TaskAssignee.objects.filter(user=staff_user)
        subtasks = SubTasks.objects.filter(task=task, is_active=True).prefetch_related(
            Prefetch(
                "task_assignee",
                queryset=rated_subtasks.order_by("-date"),
                to_attr="rated_data",
            )
        )

        if request.method == "POST":
            subtask_id = request.POST.get("subtask_id")
            rate = float(request.POST.get("rate"))
            comment = request.POST.get("comment")
            date = request.POST.get("date")

            subtask = SubTasks.objects.get(id=subtask_id)
            if rate < subtask.min_range or rate > subtask.max_range:
                messages.error(
                    request,
                    f"Rating should be between {subtask.min_range} and {subtask.max_range}",
                )
                return redirect(
                    "rate_user_task_assign", task_id=task_id, staff_id=staff_id
                )

            # Create or update the TaskAssignee instance
            assignee = TaskAssignee.objects.create(
                subtask=subtask,
                user=staff_user,
                rating=rate,
                comment=comment,
                date=date,
            )

            messages.success(request, "Baho mufaqiyatli saqlandi")
            return redirect("rate_user_task_assign", task_id=task_id, staff_id=staff_id)

        context = {
            "task": task,
            "staff_user": staff_user,
            "subtasks": subtasks,
        }
        return render(
            request,
            "tasks/create_user_subtasks_list.html",
            context,
        )
    except Exception as e:
        messages.error(request, f"Error: {e}")
        raise e


@login_required
def user_task_assigments(request, user_id, task_id=None):
    try:
        from_date = request.GET.get("from_date", "")
        to_date = request.GET.get("to_date", "")

        user = get_object_or_404(CustomUser, id=user_id)
        task_assignments = TaskAssignee.objects.filter(user=user).order_by("-date")
        if task_id:
            task = Tasks.objects.get(id=task_id)
            sub_tasks = SubTasks.objects.filter(task=task)
            task_assignments = task_assignments.filter(subtask__in=sub_tasks)

        if from_date != "" and to_date != "":
            task_assignments = task_assignments.filter(date__range=[from_date, to_date])

        context = {
            "user": user,
            "task": task if task_id else None,
            "sub_tasks": sub_tasks if task_id else None,
            "task_assignments": task_assignments,
            "from_date": from_date,
            "to_date": to_date,
        }
        return render(
            request,
            "tasks/user_task_assignments.html",
            context,
        )
    except Exception as e:
        raise e

tasks/views/tasks.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import models
from django.db.models import Prefetch, Q, Sum, Value
from django.db.models.functions import Coalesce
from django.shortcuts import redirect, render

from accounts.models import CustomUser, UserRole
from tasks.models import SubTasks, TaskAssignee, Tasks


@login_required
def tasks_list(request):
    tasks = Tasks.objects.filter(is_active=True)
    return render(request, "tasks/tasks_list.html", {"tasks": tasks})


@login_required
def subtasks_list(request, task_id):
    try:
        task = Tasks.objects.get(id=task_id)
        subtasks = SubTasks.objects.filter(task=task, is_active=True)

        # Annotate total ratings for staff_users, ensuring None becomes 0
        staff_users = (
            CustomUser.objects.filter(is_active=True, role=UserRole.USER)
            .prefetch_related(
                Prefetch(
                    "task_assignee",
                    queryset=TaskAssignee.objects.filter(subtask__in=subtasks),
                    to_attr="rated_data",
                )
            )
            .annotate(
                total_rating=Coalesce(
                    Sum(
                        "task_assignee__rating",
                        filter=Q(task_assignee__subtask__in=subtasks),
                    ),
                    Value(0),
                    output_field=models.FloatField(),
                )
            )
        )
        context = {
            "subtasks": subtasks,
            "task": task,
            "staff_users": staff_users,
        }
        return render(request, "tasks/subtasks_list.html", context)
    except Exception as e:
        raise e

templates/tasks/create_user_subtasks_list.html
{% extends 'base/base.html' %}

{% block content %}

<!-- Responsive Table -->
<h4 class="fw-bold"><span class="text-muted fw-light"> <a href="{% url 'subtasks_list' task.id %}">Xodimlar</a> /</span>
    Baholash</h4>

<div class="card" style="height: calc(100vh - 200px);">
    <h5 class="card-header">
        <b>{{task.title}} </b> - {{staff_user.full_name}} baholash
    </h5>
    <div class="table-responsive text-nowrap">
        <table class="table table-bordered table-fit table-fixed">
            <thead>
                <tr class="text-wrap">
                    <th class="th-lg">#</th>
                    <th class="text-wrap">
                        Vazifalar (ball)
                    </th>
                    <th>Baho</th>
                    <th>Sana</th>
                    <th>Izoh</th>
                </tr>
            </thead>

            <tbody>
                {% for subtask in subtasks %}
                <tr class="text-wrap">
                    <td class="th-lg">{{ forloop.counter }}</td>

                    <td>
                        <b>
                            {{ subtask.title }} <small>({{subtask.min_range}} - {{subtask.max_range}})</small>
                        </b>
                    </td>
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="subtask_id" value="{{ subtask.id }}">

                        <td>

                            <input type="number" step=any class="form-control" name="rate" placeholder="Ball"
                                min="{{subtask.min_range}}" max="{{subtask.max_range}}" required>

                        </td>
                        <td>

                            <input type="date" class="form-control" name="date" placeholder="Sana" required>
                        </td>
                        <td>

                            <textarea class="form-control" name="comment" placeholder="Izoh" required>
                                    </textarea>
                            <button type="submit" class="btn btn-success mt-2">
                                Saqlash
                            </button>
                        </td>
                    </form>

                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-center">No data</td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
<!--/ Responsive Table -->


{% endblock %}

templates/tasks/rate_user_subtasks_list.html
{% extends 'base/base.html' %}

{% block content %}

<!-- Responsive Table -->
<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light"> <a
            href="{% url 'subtasks_list' task.id %}">Xodimlar</a> /</span> Baholash</h4>

<div class="card">
    <h5 class="card-header">
        <b>{{task.title}} </b> - {{staff_user.full_name}} baholash
    </h5>
    <div class="table-responsive text-nowrap">
        <table class="table table-bordered">
            <thead>
                <tr class="text-nowrap">
                    <th>#</th>
                    <th class="text-center">Vazifalar (ball)</th>
                    <th class="text-center">Baholash</th>
                </tr>
            </thead>

            <tbody>
                {% for subtask in subtasks %}
                <tr>
                    <th scope="row">{{ subtask.id }}</th>
                    <td>{{ subtask.title }} <small>({{subtask.min_range}} - {{subtask.max_range}})</small> </td>
                    <td class="text-center">
                        <form method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="subtask_id" value="{{ subtask.id }}">
                            <div class="row">
                                <div class="col-md-4 mb-3">
                                    <input type="number" class="form-control" name="rate" placeholder="Rate"
                                        value="{% if subtask.rated_data and subtask.rated_data.0.rating %}{{ subtask.rated_data.0.rating }}{% endif %}"
                                        required>
                                </div>
                                <div class="col-md-4 mb-3">
                                    <input type="text" class="form-control" name="comment" placeholder="Comment"
                                        value="{% if subtask.rated_data and subtask.rated_data.0.comment %}{{ subtask.rated_data.0.comment }}{% endif %}"
                                        required>
                                </div>
                                <div class="col-md-4 mb-3">
                                    <button type="submit" class="btn btn-success">Save</button>
                                </div>
                            </div>
                        </form>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3" class="text-center">No data</td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
<!--/ Responsive Table -->


{% endblock %}

templates/tasks/subtasks_list.html
{% extends 'base/base.html' %}

{% block content %}

<!-- Responsive Table -->
<h4 class="fw-bold"><span class="text-muted fw-light">
        <a href="{% url 'tasks_list' %}">Vazifalar</a> /</span> Xodimlar</h4>

<div class="card" style="height: calc(100vh - 200px);">
    <h5 class="card-header">
        <b>{{task.title}} </b> - baholash uchun xodimlar ro'yxati
    </h5>
    <div class="table-responsive text-nowrap">
        <table id="example" class="table table-bordered">
            <thead>
                <tr class="text-nowrap">
                    <th>#</th>
                    <th>Ismi </th>
                    <th>Berilgan loyiha</th>
                    <th>Lavozim</th>
                    <th>Baholash</th>
                    <th>Telefon raqami</th>
                    <th>Umumiy bahosi</th>
                </tr>
            </thead>
            <tbody>
                {% for staff_user in staff_users %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>

                    <td>
                        {{staff_user.full_name}}
                    </td>
                    <td>
                        {{staff_user.current_project.name}}
                    </td>
                    <td>
                        <a href="{% url 'rate_user_task_assign' task.id staff_user.id %}"
                            class="btn btn-primary">Baholash</a>
                    </td>
                    <td>
                        {{staff_user.get_position_display }}
                    </td>
                    <td>
                        {{staff_user.phone|default:"-"}}
                    </td>
                    <td>
                        {{staff_user.total_rating}}
                    </td>

                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="text-center">No data</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!--/ Responsive Table -->

{% include 'base/dataTable.html' %}


{% endblock %}

templates/tasks/swod_analysis.html
{% extends 'base/base.html' %}
{% load extra_filters %}

{% block content %}
<style>
    .stick-fixed {
        position: sticky;
        left: 0;
        background: white !important;
        z-index: 1;
    }
</style>
<!-- Responsive Table -->
<h4 class="fw-bold">SWOD tahlil</h4>

<div class="card" style="height: calc(100vh - 200px);">
    <h5 class="card-header">
        SWOD Tahliliy ma'lumotlar jadvali
    </h5>
    <div class="table-responsive text-nowrap">
        <!-- left side search and right side from to range date filter -->
        <div class="d-flex justify-content-lg-between p-3">
            <div class="d-flex">
                <!-- for Download Excel file -->
            </div>
            <!-- from to date filter -->

            <form method="get" class="d-flex justify-content-lg-end">
                <input type="date" class="form-control" placeholder="From date" aria-label="From date" name="from_date"
                    value="{{ from_date|default:"" }}" required>
                <input type="date" class="form-control" placeholder="To date" aria-label="To date" name="to_date"
                    value="{{ to_date|default:"" }}" required>
                <button class="btn btn-success" type="submit">Filter</button>
            </form>
        </div>

        <table class="table table-bordered" id="example">

            <thead>
                <tr class="text-nowrap">
                    <th>№</th>
                    <th>FISH</th>
                    {% for task in tasks %}
                    <th>{{ task.title }}</th>
                    {% endfor %}
                    <th>Bonus ({{total_users_bonus}})</th>
                    <th>Jami ({{users_total}})</th>
                    <th>KPI</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <th scope="row" class="stick-fixed">{{ forloop.counter }}</th>
                    <td class="stick-fixed" style="left: 40px;">

                        <a
                            href="{% url 'user_task_assigments' user.id 0 %}?from_date={{ from_date }}&to_date={{ to_date }}">
                            {{ user.full_name }} <br>
                            <small>
                                <!-- ( {{user.current_project.name}} <br> -->
                                ({{ user.get_position_display }})

                            </small>
                        </a>
                    </td>

                    {% with user_ratings=ratings|get_item:user.id %}
                    {% for task in tasks %}
                    <td>
                        {% with rating=user_ratings|get_task_rating:task.title %}
                        <!-- url a href link user_id and task_id  -->
                        <a
                            href="{% url 'user_task_assigments' user.id task.id %}?from_date={{ from_date }}&to_date={{ to_date }}">
                            {{ rating|default:"0,00" }}
                        </a>
                        {% endwith %}
                    </td>
                    {% endfor %}
                    {% endwith %}

                    <td>
                        {{ users_bonus|get_item:user.id|default:"0,00" }}
                    </td>
                    <td>{{ user_totals|get_item:user.id|default:"0,00" }}</td>
                    <td>{{ users_kpi|get_item:user.id|default:"0,00" }} %</td>
                </tr>
                {% empty %}
                <tr>
                    <td class="text-center">No data</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>
<!--/ Responsive Table -->
{% include 'base/dataTable.html' %}


{% endblock %}

templates/tasks/tasks_list.html
{% extends 'base/base.html' %}

{% block content %}
<h4 class="fw-bold">
    Vazifalar ro'yxati
</h4>
<div class="row">

    {% for task in tasks %}
    <div class="col-md-6 col-xl-4">
        <div class="card shadow-none bg-transparent border border-primary mb-3">
            <div class="card-body">
                <h5 class="card-title">
                    <a href="{% url 'subtasks_list' task.id %}">{{ task.title }}</a>
                </h5>
                <p class="card-text">
                    {{ task.description }}
                </p>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

templates/tasks/user_task_assignments.html
{% extends 'base/base.html' %}

{% block content %}


<!-- Responsive Table -->
<h4 class="fw-bold"><span class="text-muted fw-light">
        <a href="{% url 'swod_analysis' %}">SWOD</a> /</span> {{user.full_name}}</h4>

<div class="card">
    <div class="d-flex justify-content-lg-between p-3">
        <div class="d-flex">
            <!-- for Download Excel file -->
            <b>{{task.title}} </b> - bo'yicha xodimning ishlari

        </div>
        <!-- from to date filter -->

        <form method="get" class="d-flex justify-content-lg-end">
            <input type="date" class="form-control" placeholder="From date" aria-label="From date" name="from_date"
                value="{{ from_date|default:"" }}" required>
            <input type="date" class="form-control" placeholder="To date" aria-label="To date" name="to_date"
                value="{{ to_date|default:"" }}" required>
            <button class="btn btn-success" type="submit">Filter</button>
        </form>
    </div>

    <div class="table-responsive text-nowrap">
        <table id="example" class="table table-bordered">
            <thead>
                <tr class="text-nowrap">
                    <th>#</th>
                    <th>Vazifa nomi </th>
                    <th>Berilgan ball</th>
                    <th>Izoh</th>
                    <th>Sana</th>
                </tr>
            </thead>
            <tbody>
                {% for task_assignment in task_assignments %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        {{task_assignment.subtask.title}}
                        ({{task_assignment.subtask.min_range}} - {{task_assignment.subtask.max_range}})
                    </td>
                    <td>
                        {{task_assignment.rating}}

                    </td>
                    <td>
                        {{task_assignment.comment}}

                    </td>
                    <td>
                        {{task_assignment.date|date:"d-m-Y"|default:"Mavjud emas"}}
                    </td>

                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="text-center">No data</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!--/ Responsive Table -->

{% include 'base/dataTable.html' %}

{% endblock %}